### ISSUE TITLE
On goplus startup, complaints during load of golangci

### ISSUE THREAD

**Issue by WyoMurf** [joefitzgerald/go-plus#1057]
When I first open a .go file for edit, the goplus stuff loads, and I see:

$ go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
# github.com/golangci/golangci-lint/pkg/golinters
../src/github.com/golangci/golangci-lint/pkg/golinters/gci.go:50:25: assignment mismatch: 3 variables but gci.Run returns 2 values
../src/github.com/golangci/golangci-lint/pkg/golinters/golint.go:21:14: l.LintPkg undefined (type *"github.com/golangci/lint-1".Linter has no field or method LintPkg)
../src/github.com/golangci/golangci-lint/pkg/golinters/gomnd.go:13:6: cannot use magic_numbers.Analyzer (type *"github.com/tommy-muehle/go-mnd/vendor/golang.org/x/tools/go/analysis".Analyzer) as type *"golang.org/x/tools/go/analysis".Analyzer in array or slice literal
../src/github.com/golangci/golangci-lint/pkg/golinters/unused.go:16:7: undefined: unused.NewChecker

$ go get -u github.com/zmb3/gogetdoc
$ go get -u github.com/zmb3/goaddimport### Help, format on save stopped working when I upgraded to v6.0.0+
...

I am wondering if some of the lint errors I see when I save some files, that don't appear to have any problems, are the result of these problems?

murf
